version: '3'
services:
  osm-db:
    image: chatelao/docker-postgres-osm
    environment:
      OSM_USER:
      OSM_DB:
    volumes:
      - osm_postgres_database:/var/lib/postgresql/data

    networks:
      - osm_network

  tile-server:
    build: ./tile-server-container
    image: bwindsor/osm-tiles
    depends_on:
      - osm-db
    ports:
      - 80:8000
    networks:
      - osm_network

networks:
  osm_network:
    external: true

volumes:
  osm_postgres_database: