version: '3.2'
services:
  data-importer:
    image: openfirmware/osm2pgsql
    volumes:
      - type: bind
        source: ${IMPORT_FROM}
        target: /osm

    entrypoint: ""
    command: osm2pgsql --create --slim --cache 1000 --cache-strategy sparse --database ${OSM_DB} --username ${OSM_USER} --host osm-db --port 5432 /osm/${IMPORT_FILE}
    networks:
      - osm_network

networks:
  osm_network:
    external: true