version: '3'
services:
  osm-db:
    image: chatelao/docker-postgres-osm
    environment:
      OSM_USER:
      OSM_DB:
    volumes:
      - osm_postgres_database:/var/lib/postgresql/data

  tile-server:
    image: smartroadsense/osm-tiles
    depends_on:
      - osm-db
    ports:
      - 80:8000

volumes:
  osm_postgres_database:
    external: true