#!/bin/bash
# Create new containers, making sure we build, and detach from them
docker-compose up --build -d
# Wait to make sure containers are properly up and running
sleep 20s
# Restart containers
docker-compose stop
docker-compose start